---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Start node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true
  become: true

- name: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted
    enabled: true
  become: true

- name: Start fail2ban_exporter
  ansible.builtin.service:
    name: fail2ban_exporter
    state: started
    enabled: true
  become: true

- name: Restart fail2ban_exporter
  ansible.builtin.service:
    name: fail2ban_exporter
    state: restarted
    enabled: true
  become: true

- name: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
    enabled: true
  become: true
