---
- name: Restart external monitor stack
  ansible.builtin.systemd:
    name: "{{ service_item }}"
    state: restarted
  loop:
    - external-loki
    - external-prometheus
    - external-grafana
  loop_control:
    loop_var: service_item
  become: true

- name: Reload ufw
  community.general.ufw:
    state: reloaded
